### PR TITLE
@HuiSF feat(appsync-dart-visior): Genearting dart class for CustomType (non-model)

### LINKED ISSUE #233: `amplify codegen models` genarates emply model for flutter with no @model directive
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

5.3.0

### What operating system are you using?

macOS Big Sur 11.5.2 (on MBP 2018 - Intel )

### Amplify Codegen Command

codegen models

## description

This bug occur on types defined without `@model` directive.

The CLI does generate dart files under `<project-dire>/lib/models` with proper filename. However, inside generated files, class definition codes were missing. There were only license declarations and default imports.

## example

With schema.graphql below, 

```schema.graphql

type Stuff @model {
  id: ID!
  name: String
  stuffType: StuffType 
}

type StuffType {
  typeName: String
}

```

the CLI `amplify codegen models` generates following files.

```
<project-root> / lib / models
 - ModelProvider.dart
 - Stuff.dart
 - StuffType.dart
```

`ModelProvider.dart` 

```ModelProvider.dart
/*
* Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License").
* You may not use this file except in compliance with the License.
* A copy of the License is located at
*
*  http://aws.amazon.com/apache2.0
*
* or in the "license" file accompanying this file. This file is distributed
* on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
* express or implied. See the License for the specific language governing
* permissions and limitations under the License.
*/

// ignore_for_file: public_member_api_docs

import 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart';
import 'Stuff.dart';

export 'Stuff.dart';

class ModelProvider implements ModelProviderInterface {
  @override
  String version = "203d2cbaaae246faa9c7505e675cd8c8";
  @override
  List<ModelSchema> modelSchemas = [Stuff.schema];
  static final ModelProvider _instance = ModelProvider();

  static ModelProvider get instance => _instance;
  
  ModelType getModelTypeByModelName(String modelName) {
    switch(modelName) {
    case "Stuff": {
    return Stuff.classType;
    }
    break;
    default: {
    throw Exception("Failed to find model in model provider for model name: " + modelName);
    }
    }
  }
}
```

`Stuff.dart`

```Stuff.dart
/*
* Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License").
* You may not use this file except in compliance with the License.
* A copy of the License is located at
*
*  http://aws.amazon.com/apache2.0
*
* or in the "license" file accompanying this file. This file is distributed
* on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
* express or implied. See the License for the specific language governing
* permissions and limitations under the License.
*/

// ignore_for_file: public_member_api_docs

import 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart';
import 'package:flutter/foundation.dart';


/** This is an auto generated class representing the Stuff type in your schema. */
@immutable
class Stuff extends Model {
  static const classType = const _StuffModelType();
  final String id;
  final String? _name;
  final StuffType? _stuffType;

  @override
  getInstanceType() => classType;
  
  @override
  String getId() {
    return id;
  }
  
  String? get name {
    return _name;
  }
  
  StuffType? get stuffType {
    return _stuffType;
  }
  
  const Stuff._internal({required this.id, name, stuffType}): _name = name, _stuffType = stuffType;
  
  factory Stuff({String? id, String? name, StuffType? stuffType}) {
    return Stuff._internal(
      id: id == null ? UUID.getUUID() : id,
      name: name,
      stuffType: stuffType);
  }
  
  bool equals(Object other) {
    return this == other;
  }
  
  @override
  bool operator ==(Object other) {
    if (identical(other, this)) return true;
    return other is Stuff &&
      id == other.id &&
      _name == other._name &&
      _stuffType == other._stuffType;
  }
  
  @override
  int get hashCode => toString().hashCode;
  
  @override
  String toString() {
    var buffer = new StringBuffer();
    
    buffer.write("Stuff {");
    buffer.write("id=" + "$id" + ", ");
    buffer.write("name=" + "$_name" + ", ");
    buffer.write("stuffType=" + (_stuffType != null ? _stuffType!.toString() : "null"));
    buffer.write("}");
    
    return buffer.toString();
  }
  
  Stuff copyWith({String? id, String? name, StuffType? stuffType}) {
    return Stuff(
      id: id ?? this.id,
      name: name ?? this.name,
      stuffType: stuffType ?? this.stuffType);
  }
  
  Stuff.fromJson(Map<String, dynamic> json)  
    : id = json['id'],
      _name = json['name'],
      _stuffType = json['stuffType'];
  
  Map<String, dynamic> toJson() => {
    'id': id, 'name': _name, 'stuffType': _stuffType
  };

  static final QueryField ID = QueryField(fieldName: "stuff.id");
  static final QueryField NAME = QueryField(fieldName: "name");
  static final QueryField STUFFTYPE = QueryField(fieldName: "stuffType");
  static var schema = Model.defineSchema(define: (ModelSchemaDefinition modelSchemaDefinition) {
    modelSchemaDefinition.name = "Stuff";
    modelSchemaDefinition.pluralName = "Stuffs";
    
    modelSchemaDefinition.addField(ModelFieldDefinition.id());
    
    modelSchemaDefinition.addField(ModelFieldDefinition.field(
      key: Stuff.NAME,
      isRequired: false,
      ofType: ModelFieldType(ModelFieldTypeEnum.string)
    ));
    
    modelSchemaDefinition.addField(ModelFieldDefinition.field(
      key: Stuff.STUFFTYPE,
      isRequired: false,
      ofType: ModelFieldType(ModelFieldTypeEnum.string)
    ));
  });
}

class _StuffModelType extends ModelType<Stuff> {
  const _StuffModelType();
  
  @override
  Stuff fromJson(Map<String, dynamic> jsonData) {
    return Stuff.fromJson(jsonData);
  }
}
```

`StuffType.dart`

```StuffType.dart
/*
* Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License").
* You may not use this file except in compliance with the License.
* A copy of the License is located at
*
*  http://aws.amazon.com/apache2.0
*
* or in the "license" file accompanying this file. This file is distributed
* on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
* express or implied. See the License for the specific language governing
* permissions and limitations under the License.
*/

// ignore_for_file: public_member_api_docs

import 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart';
import 'package:flutter/foundation.dart';

```

### Expected behavior

Class definition should be generated inside `StuffType.dart` file.

### Reproduction steps

Please see `example` section in the description above.

### GraphQL schema(s)

<details>

```graphql
type Stuff @model {
  id: ID!
  name: String
  stuffType: StuffType 
}

type StuffType {
  typeName: String
}

```

</details>

### Log output

<details>

```
2021-08-23T03:16:30.065Z|info : amplify models codegen  
2021-08-23T03:16:30.125Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}

```

</details>

### Additional information

Perhaps related to this issue.

https://github.com/aws-amplify/amplify-cli/issues/2988#

### PR DESCRIPTION
**Pull request by HuiSF**
#### Issue #, if available

fix #233 
Feature request issue: https://github.com/aws-amplify/amplify-flutter/issues/260

#### Description of how you validated changes

Added unit tests to test use cases:

* CustomType
* CustomType nests CustomType
* Model nests CustomType and list of CustomType

Should not expecting breaking change as CustomType is a feature addition.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are changed and added
- [x] Changes are tested using sample applications for all relevant platforms (iOS/android/flutter/Javascript) that use the feature added/modified

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dnys1** [comment]
Can we add `toString` back as well as `copyWith`?

**Comment by HuiSF** [comment]
@AaronZyLee Updated the test cases with nullsafety disabled, and added `copyWith` and `toString` methods to non-model Dart classes according to @dnys1 's suggestion. Could you please review again, thanks!

**Review by AaronZyLee — APPROVED** [review]

File: packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts [hunk 1]
```diff
@@ -108,16 +118,16 @@ export class AppSyncModelDartVisitor<
       .implements([`${LOADER_CLASS_NAME}Interface`])
       .addClassMember('version', 'String', `"${this.computeVersion()}"`, undefined, ['override'])
       .addClassMember('modelSchemas', 'List<ModelSchema>', `[${modelNames.map(m => `${m}.schema`).join(', ')}]`, undefined, ['override'])
+      .addClassMember('customTypeSchemas', 'List<ModelSchema>', `[${nonModelNames.map(nm => `${nm}.schema`).join(', ')}]`, undefined, ['override'])
```
Comment (HuiSF) [inline packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts:121]: This field now needs to be conditionally inserted for amplify-flutter version 0.3.0 and above.
(For preview release the version check may need to contain 0.3.0.rc.2)
